// Code generated by protoc-gen-go.
// source: github.com/michaeldye/synchrophasor-proto/synchrophasor_dpe/synchrophasor_store.proto
// DO NOT EDIT!

/*
Package synchrophasor_dpe is a generated protocol buffer package.

It is generated from these files:
	github.com/michaeldye/synchrophasor-proto/synchrophasor_dpe/synchrophasor_store.proto

It has these top-level messages:
	HorizonDatumWrapper
	DPEResponse
*/
package synchrophasor_dpe

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pmu_server "github.com/michaeldye/synchrophasor-proto/pmu_server"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HorizonDatumWrapper struct {
	Type        string                         `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	Lat         float32                        `protobuf:"fixed32,2,opt,name=Lat" json:"Lat,omitempty"`
	Lon         float32                        `protobuf:"fixed32,3,opt,name=Lon" json:"Lon,omitempty"`
	AgreementID string                         `protobuf:"bytes,4,opt,name=AgreementID" json:"AgreementID,omitempty"`
	DeviceID    string                         `protobuf:"bytes,5,opt,name=DeviceID" json:"DeviceID,omitempty"`
	HAPartners  []string                       `protobuf:"bytes,6,rep,name=HAPartners" json:"HAPartners,omitempty"`
	Datum       *pmu_server.SynchrophasorDatum `protobuf:"bytes,7,opt,name=Datum" json:"Datum,omitempty"`
}

func (m *HorizonDatumWrapper) Reset()                    { *m = HorizonDatumWrapper{} }
func (m *HorizonDatumWrapper) String() string            { return proto.CompactTextString(m) }
func (*HorizonDatumWrapper) ProtoMessage()               {}
func (*HorizonDatumWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HorizonDatumWrapper) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HorizonDatumWrapper) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *HorizonDatumWrapper) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *HorizonDatumWrapper) GetAgreementID() string {
	if m != nil {
		return m.AgreementID
	}
	return ""
}

func (m *HorizonDatumWrapper) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *HorizonDatumWrapper) GetHAPartners() []string {
	if m != nil {
		return m.HAPartners
	}
	return nil
}

func (m *HorizonDatumWrapper) GetDatum() *pmu_server.SynchrophasorDatum {
	if m != nil {
		return m.Datum
	}
	return nil
}

type DPEResponse struct {
}

func (m *DPEResponse) Reset()                    { *m = DPEResponse{} }
func (m *DPEResponse) String() string            { return proto.CompactTextString(m) }
func (*DPEResponse) ProtoMessage()               {}
func (*DPEResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*HorizonDatumWrapper)(nil), "synchrophasor_dpe.HorizonDatumWrapper")
	proto.RegisterType((*DPEResponse)(nil), "synchrophasor_dpe.DPEResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SynchrophasorDPE service

type SynchrophasorDPEClient interface {
	Store(ctx context.Context, opts ...grpc.CallOption) (SynchrophasorDPE_StoreClient, error)
}

type synchrophasorDPEClient struct {
	cc *grpc.ClientConn
}

func NewSynchrophasorDPEClient(cc *grpc.ClientConn) SynchrophasorDPEClient {
	return &synchrophasorDPEClient{cc}
}

func (c *synchrophasorDPEClient) Store(ctx context.Context, opts ...grpc.CallOption) (SynchrophasorDPE_StoreClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SynchrophasorDPE_serviceDesc.Streams[0], c.cc, "/synchrophasor_dpe.SynchrophasorDPE/Store", opts...)
	if err != nil {
		return nil, err
	}
	x := &synchrophasorDPEStoreClient{stream}
	return x, nil
}

type SynchrophasorDPE_StoreClient interface {
	Send(*HorizonDatumWrapper) error
	CloseAndRecv() (*DPEResponse, error)
	grpc.ClientStream
}

type synchrophasorDPEStoreClient struct {
	grpc.ClientStream
}

func (x *synchrophasorDPEStoreClient) Send(m *HorizonDatumWrapper) error {
	return x.ClientStream.SendMsg(m)
}

func (x *synchrophasorDPEStoreClient) CloseAndRecv() (*DPEResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DPEResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SynchrophasorDPE service

type SynchrophasorDPEServer interface {
	Store(SynchrophasorDPE_StoreServer) error
}

func RegisterSynchrophasorDPEServer(s *grpc.Server, srv SynchrophasorDPEServer) {
	s.RegisterService(&_SynchrophasorDPE_serviceDesc, srv)
}

func _SynchrophasorDPE_Store_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SynchrophasorDPEServer).Store(&synchrophasorDPEStoreServer{stream})
}

type SynchrophasorDPE_StoreServer interface {
	SendAndClose(*DPEResponse) error
	Recv() (*HorizonDatumWrapper, error)
	grpc.ServerStream
}

type synchrophasorDPEStoreServer struct {
	grpc.ServerStream
}

func (x *synchrophasorDPEStoreServer) SendAndClose(m *DPEResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *synchrophasorDPEStoreServer) Recv() (*HorizonDatumWrapper, error) {
	m := new(HorizonDatumWrapper)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SynchrophasorDPE_serviceDesc = grpc.ServiceDesc{
	ServiceName: "synchrophasor_dpe.SynchrophasorDPE",
	HandlerType: (*SynchrophasorDPEServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Store",
			Handler:       _SynchrophasorDPE_Store_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/michaeldye/synchrophasor-proto/synchrophasor_dpe/synchrophasor_store.proto",
}

func init() {
	proto.RegisterFile("github.com/michaeldye/synchrophasor-proto/synchrophasor_dpe/synchrophasor_store.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0xcd, 0x6a, 0x32, 0x31,
	0x14, 0x86, 0xbf, 0xf1, 0xef, 0xab, 0x47, 0x0a, 0x36, 0xdd, 0x04, 0x17, 0x32, 0xb8, 0x28, 0xb3,
	0x69, 0x04, 0xdb, 0x1b, 0x10, 0x46, 0x50, 0x68, 0x41, 0xc6, 0x96, 0x2e, 0x25, 0x8e, 0x07, 0x67,
	0xa0, 0x93, 0x84, 0x93, 0x28, 0x4c, 0xef, 0xb6, 0x77, 0x52, 0x8c, 0xa5, 0x1d, 0x7f, 0x16, 0xdd,
	0x9d, 0x3c, 0x79, 0xc2, 0x9b, 0xf3, 0xc2, 0xeb, 0x26, 0x77, 0xd9, 0x76, 0x25, 0x52, 0x5d, 0x0c,
	0x8b, 0x3c, 0xcd, 0x24, 0xbe, 0xaf, 0x4b, 0x1c, 0xda, 0x52, 0xa5, 0x19, 0x69, 0x93, 0x49, 0xab,
	0xe9, 0xde, 0x90, 0x76, 0xfa, 0x98, 0x2d, 0xd7, 0xe6, 0xc4, 0x5a, 0x5a, 0xa7, 0x09, 0x85, 0x77,
	0xd9, 0xcd, 0x99, 0xdc, 0x7b, 0xfe, 0x7b, 0x92, 0x29, 0xb6, 0x4b, 0x8b, 0xb4, 0x43, 0x3a, 0x0d,
	0x95, 0x4e, 0x1e, 0x12, 0x06, 0x9f, 0x01, 0xdc, 0x4e, 0x35, 0xe5, 0x1f, 0x5a, 0xc5, 0xd2, 0x6d,
	0x8b, 0x37, 0x92, 0xc6, 0x20, 0x31, 0x06, 0x8d, 0x97, 0xd2, 0x20, 0x0f, 0xc2, 0x20, 0x6a, 0x27,
	0x7e, 0x66, 0x5d, 0xa8, 0x3f, 0x49, 0xc7, 0x6b, 0x61, 0x10, 0xd5, 0x92, 0xfd, 0xe8, 0x89, 0x56,
	0xbc, 0xfe, 0x4d, 0xb4, 0x62, 0x21, 0x74, 0xc6, 0x1b, 0x42, 0x2c, 0x50, 0xb9, 0x59, 0xcc, 0x1b,
	0xfe, 0x79, 0x15, 0xb1, 0x1e, 0x5c, 0xc5, 0xb8, 0xcb, 0x53, 0x9c, 0xc5, 0xbc, 0xe9, 0xaf, 0x7f,
	0xce, 0xac, 0x0f, 0x30, 0x1d, 0xcf, 0x25, 0x39, 0x85, 0x64, 0x79, 0x2b, 0xac, 0x47, 0xed, 0xa4,
	0x42, 0xd8, 0x23, 0x34, 0xfd, 0x2f, 0xf9, 0xff, 0x30, 0x88, 0x3a, 0xa3, 0xbe, 0xf8, 0x5d, 0x51,
	0x2c, 0xaa, 0x2b, 0x7a, 0x2b, 0x39, 0xc8, 0x83, 0x6b, 0xe8, 0xc4, 0xf3, 0x49, 0x82, 0xd6, 0x68,
	0x65, 0x71, 0xb4, 0x81, 0xee, 0xb1, 0x3b, 0x9f, 0xb0, 0x05, 0x34, 0x17, 0xfb, 0xde, 0xd9, 0x9d,
	0x38, 0xab, 0x5c, 0x5c, 0xe8, 0xa7, 0xd7, 0xbf, 0xe0, 0x55, 0x42, 0x06, 0xff, 0xa2, 0x60, 0xd5,
	0xf2, 0x15, 0x3f, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xe5, 0xda, 0x0e, 0x1d, 0x02, 0x00,
	0x00,
}
